### ISSUE TITLE
请更新至 DCEF 3.2454.1344 版，谢谢

### ISSUE THREAD

**Issue by awenewa** [bccsafe/DcefBrowser#3]
请更新至 DCEF 3.2454.1344 版，谢谢

**Comment by himStone** [comment]
2704已经在开发了 不过可能要等一段时间

**Comment by awenewa** [comment]
谢谢，辛苦了。

2016-06-30 15:07 GMT+08:00 BccSafe notifications@github.com:

**Comment by himStone** [comment]
2704分支更新好了 不过不支持xp，所以master上是2623，也是支持xp的最后一个cef版本

2704 branch is updated but not support Windows XP(2623(master) is the last branch to support XP)
