### ISSUE TITLE
cef_message_router在dcef中该如何实现呢？

### ISSUE THREAD

**Issue by wzyingqin** [bccsafe/DcefBrowser#4]
在cef中，cef\include\wrapper\cef_message_router.h头文件描述了以下的调用方式
//    var request_id = window.cefQuery({
//        request: 'my_request',
//        persistent: false,
//        onSuccess: function(response) {},
//        onFailure: function(error_code, error_message) {}
//    });

在DCEF中，该如何实现呢？

**Comment by himStone** [comment]
DcefBrowser做了进一步的封装

1.如果想要取js值

<pre>DcefBrowser1.JsExtention.GetAsString(DcefBrowser1.ActiveBrowser, 'Str');</pre> 

2.如果想要js和delphi交互

<pre>TClient = class
  class procedure DoTest(aName: string);
end;
class procedure TClient.DoTest(aName: string);
begin
  //get aName from js
end;
DcefBApp.RegisterClasses(TClient)
TClient.DoTest("test string");//run in js and get the value in delphi
</pre>
