### ISSUE TITLE
Provide an exe of the Browser?

### ISSUE THREAD

**Issue by raelb** [bccsafe/DcefBrowser#5]
Hello,

Is it possible to provide an exe of the browser so I can see what it looks like, before going to the trouble of installing and compiling all the different components?

Thanks

**Comment by himStone** [comment]
https://pan.baidu.com/s/1pLTdegN

**Comment by raelb** [comment]
Thanks - however, seems to be impossible to download from that site. Download stops after a few MB. Is it possible to upload to other service such as Dropbox or GDrive?

**Comment by himStone** [comment]
https://www.dropbox.com/s/3obznlfsbbvtoir/BccBrowser%20V3.0%202016-08-21.zip?dl=0

**Comment by raelb** [comment]
Thanks. Works fine
